spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    root: INFO
    fi:
      poltsi: DEBUG

vempain:
  generate-missing-thumbnails:
    cron: "0 */10 * * * *"
  file-processing:
    cron: "0 */10 * * * *"
  queue-missing-video-exports:
    cron: "0 */10 * * * *"
