[versions]
release = "0.0.1-SNAPSHOT"
java = "25"
spring-boot = "4.1.1"
commons-codec = "1.22.1"
freefair-lombok = "9.8.0"
jacoco = "0.8.15"
jakarta-annotation-api = "3.0.0"
jakarta-bind-api = "4.0.5"
javacv = "1.5.14"
jjwt = "0.13.0"
jline = "4.4.2"
json = "20260814"
junit = "6.1.3"
mockito = "5.24.0"
postgresql = "42.7.13"
spring-cloud-bom = "2025.1.3"
spring-cloud-openfeign = "5.0.3"
spring-dependency-management = "1.1.7"
springdoc = "3.1.1"
swagger = "2.2.55"
testcontainers = "2.0.5"
thumbnailator = "0.4.21"
vempain-admin = "1.0.51"
vempain-auth = "1.0.29"

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
freefair-lombok = { id = "io.freefair.lombok", version.ref = "freefair-lombok" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
