import org.apache.tools.ant.filters.ReplaceTokens

plugins {
	id 'application'
	alias(libs.plugins.spring.boot)
	alias(libs.plugins.freefair.lombok)
	alias(libs.plugins.spring.dependency.management)
	id 'jacoco'
}

group = 'fi.poltsi.vempain'
version = libs.versions.release.get()

bootJar {
	archiveFileName = "${rootProject.name}-${version}.jar"
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(libs.versions.java.get())
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
	maven {
		url = "https://maven.pkg.github.com/Vempain/vempain-auth"
		credentials {
			username = project.findProperty("gpr.user") ?: System.getenv("GITHUB_ACTOR")
			password = project.findProperty("gpr.token") ?: System.getenv("GITHUB_TOKEN")
		}
	}
	maven {
		url = "https://maven.pkg.github.com/Vempain/vempain-admin-backend-api"
		credentials {
			username = project.findProperty("gpr.user") ?: System.getenv("GITHUB_ACTOR")
			password = project.findProperty("gpr.token") ?: System.getenv("GITHUB_TOKEN")
		}
	}
	maven { url = 'https://repo.spring.io/milestone' }
}

dependencies {
	implementation project(':api')
	// This needs to be built first in vempain-auth
	implementation "fi.poltsi.vempain:vempain-auth-core:${libs.versions.vempain.auth.get()}"
	implementation "fi.poltsi.vempain:vempain-auth-api:${libs.versions.vempain.auth.get()}"
	implementation "fi.poltsi.vempain:vempain-admin-backend-api:${libs.versions.vempain.admin.get()}"
	// Spring
	implementation "org.springframework.boot:spring-boot-starter-security:${libs.versions.spring.boot.get()}"
	implementation "org.springframework.boot:spring-boot-starter-webmvc:${libs.versions.spring.boot.get()}"
	implementation "org.springframework.boot:spring-boot-starter-web-services:${libs.versions.spring.boot.get()}"
	implementation "org.springframework.boot:spring-boot-starter-data-jpa:${libs.versions.spring.boot.get()}"
	implementation "org.springframework.boot:spring-boot-starter-actuator:${libs.versions.spring.boot.get()}"
	implementation "org.springframework.boot:spring-boot-starter-flyway:${libs.versions.spring.boot.get()}"
	implementation "org.springframework.boot:spring-boot-starter-jackson:${libs.versions.spring.boot.get()}"
	implementation "org.springframework.boot:spring-boot-starter-validation:${libs.versions.spring.boot.get()}"
	developmentOnly "org.springframework.boot:spring-boot-docker-compose:${libs.versions.spring.boot.get()}"
	implementation "io.jsonwebtoken:jjwt-api:${libs.versions.jjwt.get()}"
	implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:${libs.versions.springdoc.get()}"
	implementation "jakarta.xml.bind:jakarta.xml.bind-api:${libs.versions.jakarta.bind.api.get()}"
	implementation "jakarta.annotation:jakarta.annotation-api:${libs.versions.jakarta.annotation.api.get()}"
	implementation "commons-codec:commons-codec:${libs.versions.commons.codec.get()}"
	implementation "org.json:json:${libs.versions.json.get()}"
	implementation "org.springframework.cloud:spring-cloud-starter-openfeign:${libs.versions.spring.cloud.openfeign.get()}"
	implementation "net.coobird:thumbnailator:${libs.versions.thumbnailator.get()}"
	implementation "org.bytedeco:javacv-platform:${libs.versions.javacv.get()}"
	runtimeOnly "io.jsonwebtoken:jjwt-impl:${libs.versions.jjwt.get()}"
	runtimeOnly "io.jsonwebtoken:jjwt-jackson:${libs.versions.jjwt.get()}"
	runtimeOnly "org.postgresql:postgresql:${libs.versions.postgresql.get()}"
	testImplementation "org.springframework.boot:spring-boot-starter-test:${libs.versions.spring.boot.get()}"
	testImplementation "org.springframework.boot:spring-boot-starter-security-test:${libs.versions.spring.boot.get()}"
	testImplementation "org.springframework.boot:spring-boot-starter-webmvc-test:${libs.versions.spring.boot.get()}"
	testImplementation "org.springframework.boot:spring-boot-starter-data-jpa-test:${libs.versions.spring.boot.get()}"
	testImplementation platform("org.junit:junit-bom:${libs.versions.junit.get()}")
	testImplementation "org.junit.jupiter:junit-jupiter:${libs.versions.junit.get()}"
	testImplementation "org.testcontainers:testcontainers-junit-jupiter:${libs.versions.testcontainers.get()}"
	testImplementation "org.testcontainers:testcontainers-postgresql:${libs.versions.testcontainers.get()}"
	testImplementation "org.mockito:mockito-junit-jupiter:${libs.versions.mockito.get()}"
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${libs.versions.spring.cloud.bom.get()}"
	}
}

test {
	useJUnitPlatform()
	finalizedBy jacocoTestReport
}

jacocoTestReport {
	dependsOn test
	reports {
		xml.required = true
		html.required = true
	}
}

jacocoTestCoverageVerification {
	dependsOn test
	violationRules {
		rule {
			element = 'PACKAGE'
			includes = ['fi.poltsi.vempain.file.service.files']
			limit {
				counter = 'LINE'
				value = 'COVEREDRATIO'
				minimum = 0.95
			}
		}
	}
}

processResources {
	// capture once at configuration time (CC-safe)
	def ver = version.toString()
	// declare as input for configuration cache
	inputs.property("projectVersion", ver)

	filesMatching("**/application.yaml") {
		filteringCharset = "UTF-8"
		filter(ReplaceTokens,
				tokens: [projectVersion: ver]
		)
	}
}
